name: 'Issues Translator'
description: 'The action for translating Non-English issues content to English.'
author: 'tomsun28'
branding:
  icon: 'disc'
  color: 'orange'

inputs:
  token:
    description: 'The issue comment bot GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  IS_MODIFY_TITLE: 
    description: 'Is need modify issue title, true or false, default false.'
  CUSTOM_BOT_NOTE:
    description: 'Custom bot note message.'
runs:
  using: 'node16'
  main: 'dist/index.js'
